### ISSUE TITLE
BRHRE2 files fail to open

### ISSUE THREAD

**Issue by ToonLucas22** [chrislo27/RhythmHeavenRemixEditor2#95]
### Prerequisites
* [x] This issue specifically has something to do with RHRE2
* [x] I have attempted to [look for similar issues](https://github.com/chrislo27/RhythmHeavenRemixEditor/issues?utf8=%E2%9C%93&q=is%3Aissue)
already

### Description
Sometimes BHRE2 files don't open. Here's the stacktrace of what I believe is the issue (I attempted to open the file twice):
`Failed to load C:\Users\lucas\Downloads\RH Custom Remixes\Gigamix ENGLISH.brhre2
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at chrislo27.rhre.LoadScreen.attemptLoad(SaveLoadScreens.kt:383)
        at chrislo27.rhre.LoadScreen.access$attemptLoad(SaveLoadScreens.kt:202)
        at chrislo27.rhre.LoadScreen$showPicker$thread$1.run(SaveLoadScreens.kt:422)
Failed to load C:\Users\lucas\Downloads\RH Custom Remixes\Gigamix ENGLISH.brhre2
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at chrislo27.rhre.LoadScreen.attemptLoad(SaveLoadScreens.kt:383)
        at chrislo27.rhre.LoadScreen.access$attemptLoad(SaveLoadScreens.kt:202)
        at chrislo27.rhre.LoadScreen$showPicker$thread$1.run(SaveLoadScreens.kt:422)`

It's particularly annoying as the only solution for this is to restart the program, and even then it still has a chance of failing to open BRHRE2 files. RHRE2 files work just fine, but they were failing to open after I attempted to open the BRHRE2 files.

**Comment by chrislo27** [comment]
Upload the brhre2 file somewhere. Please fill out the template correctly (what version are you using?)

**Comment by ToonLucas22** [comment]
This is the file in question:
https://www.dropbox.com/s/9qlb597hrocchy9/Gigamix%20ENGLISH.brhre2?dl=0

I was using v2.9.0 but I remember this happening in a lot of earlier versions, like v2.5.x

**Comment by chrislo27** [comment]
I looked in your brhre2 file and it is corrupt (the music file is empty). Open it with an archive editor (7zip or WinRAR), take out the data.json file, load that (optionally rename as rhre2), and re-add the music and save again. If this is recurring, recomment on this issue, otherwise I will close it.
